version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_NAME: postgres
    logging:
      driver: "loki"
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    depends_on:
      - db
    networks:
      - mynetwork

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
