# Generated by Django 4.0 on 2025-04-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('shopapp', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myauth.profile'),
            preserve_default=False,
        ),
    ]
