# Generated by Django 4.2 on 2025-05-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_product_crated_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
